services:
    nuxt:
      image: "node:lts"
      container_name: "nuxt"
      user: "node"
      working_dir: "/usr/src/app"
      environment:
        - NODE_ENV=development
      volumes:
        - ./:/usr/src/app
      ports:
        - "3000:3000"
        - "24678:24678"
      command: "npm run dev"
    mongo:
      image: mongo:latest
      container_name: "mongo"
      working_dir: "/data/db"
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      volumes:
      - ./db:/data/db
      ports:
        - "27017:27017"